<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <base href="<?= PATH ?>">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Web Chat Mabu - Com WebSocket</title>
    <link rel="stylesheet" href="<?= PATH ?>assets/css/default.css">
    <style>
        .qr-code {
            width: 300px;
            height: 300px;
            border: 1px solid #000;
            margin: 10px;
            background-color: #e3e3e3;
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>


<div class="content">
    <h3>Pegue o QRCODE</h3>
    <div class="qr-code">
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.5.0/socket.io.js"
        integrity="sha512-ttqbKrGZiTtSLguBZ2xNvZrhUv02IO/TRq5U6TG5TK90wbaXWup5kIJ1A1tLzjOk5Mea/G4seVNrU+lwTLfAzA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    const socket = io('<?= SOCKET ?>',{
        allowEIO3: false,
        credentials: true
    });

    socket.on('qrcode', data => {
       console.log(data);
       let html = `<img src="<?= PATH ?>assets/qrcode/out.png" alt="">`;
       $(".qr-code").html(html);
    });
</script>
</body>
</html>
